### ISSUE TITLE
composer require webman/action-hook 执行的时候提示这个

### ISSUE THREAD

**Issue by ketianlin** [webman-php/action-hook#1]
Could not find package webman/action-hook. It was however found via repository search, which indicates a consistency issue with the repository.

**Comment by walkor** [comment]
执行 `composer config -g --unset repos.packagist` 去掉composer代理后试下

**Comment by ketianlin** [comment]
谢谢啊，非常感谢啊,可以了。牛逼




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "webman-php/action-hook"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月7日(星期六) 下午3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [webman-php/action-hook] composer require webman/action-hook 执行的时候提示这个 (Issue #1)





 
执行 composer config -g --unset repos.packagist 去掉composer代理后试下
